"""eliminar correo de usuario

Revision ID: 732d2dfd2ff7
Revises: 91238b1602aa
Create Date: 2026-05-05 17:59:18.974639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732d2dfd2ff7'
down_revision: Union[str, None] = '91238b1602aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usuario_correo_key', 'usuario', type_='unique')
    op.drop_column('usuario', 'correo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('correo', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.create_unique_constraint('usuario_correo_key', 'usuario', ['correo'])
    # ### end Alembic commands ###
