"""add index detalle_matricula estado

Revision ID: 91238b1602aa
Revises: c489f95eca72
Create Date: 2026-05-03 15:35:43.147237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91238b1602aa'
down_revision: Union[str, None] = 'c489f95eca72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_detalle_matricula_estado'), 'detalle_matricula', ['estado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_matricula_estado'), table_name='detalle_matricula')
    # ### end Alembic commands ###
