"""añadir documento a estudiante

Revision ID: b023178abd10
Revises: c509474f3370
Create Date: 2026-05-12 13:57:24.136784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b023178abd10'
down_revision: Union[str, None] = 'c509474f3370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudiante', sa.Column('documento', sa.String(length=10), nullable=False))
    op.drop_column('usuario', 'documento')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('documento', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_column('estudiante', 'documento')
    # ### end Alembic commands ###
