"""initial_schema

Revision ID: c489f95eca72
Revises: 
Create Date: 2026-05-03 14:52:04.590846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c489f95eca72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id_auditoria', sa.Integer(), nullable=False),
    sa.Column('tabla', sa.String(length=100), nullable=True),
    sa.Column('id_registro', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=True),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_auditoria')
    )
    op.create_index(op.f('ix_auditoria_id_auditoria'), 'auditoria', ['id_auditoria'], unique=False)
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_index(op.f('ix_categoria_id_categoria'), 'categoria', ['id_categoria'], unique=False)
    op.create_table('inventario_objeto',
    sa.Column('id_objeto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('cantidad_total', sa.Integer(), nullable=True),
    sa.Column('cantidad_disponible', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_objeto')
    )
    op.create_index(op.f('ix_inventario_objeto_id_objeto'), 'inventario_objeto', ['id_objeto'], unique=False)
    op.create_table('periodo_academico',
    sa.Column('id_periodo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_periodo')
    )
    op.create_index(op.f('ix_periodo_academico_id_periodo'), 'periodo_academico', ['id_periodo'], unique=False)
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_rol_id_rol'), 'rol', ['id_rol'], unique=False)
    op.create_table('tipo_concepto',
    sa.Column('id_tipo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipo_concepto_id_tipo'), 'tipo_concepto', ['id_tipo'], unique=False)
    op.create_table('tipo_prueba',
    sa.Column('id_tipo_prueba', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('grado_min', sa.Integer(), nullable=True),
    sa.Column('grado_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_prueba')
    )
    op.create_index(op.f('ix_tipo_prueba_id_tipo_prueba'), 'tipo_prueba', ['id_tipo_prueba'], unique=False)
    op.create_table('ubicacion',
    sa.Column('id_ubicacion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_ubicacion')
    )
    op.create_index(op.f('ix_ubicacion_id_ubicacion'), 'ubicacion', ['id_ubicacion'], unique=False)
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_usuario_id_usuario'), 'usuario', ['id_usuario'], unique=False)
    op.create_table('inventario_instrumento',
    sa.Column('id_instrumento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('id_ubicacion', sa.Integer(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_ubicacion'], ['ubicacion.id_ubicacion'], ),
    sa.PrimaryKeyConstraint('id_instrumento')
    )
    op.create_index(op.f('ix_inventario_instrumento_id_instrumento'), 'inventario_instrumento', ['id_instrumento'], unique=False)
    op.create_table('rol_usuario',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_rol', 'id_usuario')
    )
    op.create_table('salon',
    sa.Column('id_salon', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('grado', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.Integer(), nullable=False),
    sa.Column('id_periodo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_periodo'], ['periodo_academico.id_periodo'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_salon')
    )
    op.create_index(op.f('ix_salon_id_salon'), 'salon', ['id_salon'], unique=False)
    op.create_table('sesion_usuario',
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('fecha_inicio', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_expiracion', sa.TIMESTAMP(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sesion')
    )
    op.create_index(op.f('ix_sesion_usuario_id_sesion'), 'sesion_usuario', ['id_sesion'], unique=False)
    op.create_table('estudiante',
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono_acudiente', sa.String(length=20), nullable=True),
    sa.Column('id_salon', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_salon'], ['salon.id_salon'], ),
    sa.PrimaryKeyConstraint('id_estudiante')
    )
    op.create_index(op.f('ix_estudiante_id_estudiante'), 'estudiante', ['id_estudiante'], unique=False)
    op.create_index(op.f('ix_estudiante_id_salon'), 'estudiante', ['id_salon'], unique=False)
    op.create_table('inventario_libro',
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('id_salon', sa.Integer(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_salon'], ['salon.id_salon'], ),
    sa.PrimaryKeyConstraint('id_libro')
    )
    op.create_index(op.f('ix_inventario_libro_id_libro'), 'inventario_libro', ['id_libro'], unique=False)
    op.create_table('estudiante_banda',
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.PrimaryKeyConstraint('id_estudiante')
    )
    op.create_table('firmas_paz_y_salvo',
    sa.Column('id_firma', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_periodo', sa.Integer(), nullable=True),
    sa.Column('biblioteca', sa.Boolean(), nullable=True),
    sa.Column('tesoreria', sa.Boolean(), nullable=True),
    sa.Column('uniforme', sa.Boolean(), nullable=True),
    sa.Column('salon', sa.Boolean(), nullable=True),
    sa.Column('rectoria', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_periodo'], ['periodo_academico.id_periodo'], ),
    sa.PrimaryKeyConstraint('id_firma')
    )
    op.create_index(op.f('ix_firmas_paz_y_salvo_id_firma'), 'firmas_paz_y_salvo', ['id_firma'], unique=False)
    op.create_table('matricula',
    sa.Column('id_matricula', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_periodo', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_periodo'], ['periodo_academico.id_periodo'], ),
    sa.PrimaryKeyConstraint('id_matricula')
    )
    op.create_index(op.f('ix_matricula_id_matricula'), 'matricula', ['id_matricula'], unique=False)
    op.create_index(op.f('ix_matricula_id_periodo'), 'matricula', ['id_periodo'], unique=False)
    op.create_table('prestamo_instrumento',
    sa.Column('id_prestamo', sa.Integer(), nullable=False),
    sa.Column('id_instrumento', sa.Integer(), nullable=True),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('fecha_prestamo', sa.Date(), nullable=True),
    sa.Column('fecha_devolucion', sa.Date(), nullable=True),
    sa.Column('estado_entrega', sa.String(length=20), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_instrumento'], ['inventario_instrumento.id_instrumento'], ),
    sa.PrimaryKeyConstraint('id_prestamo')
    )
    op.create_index(op.f('ix_prestamo_instrumento_id_prestamo'), 'prestamo_instrumento', ['id_prestamo'], unique=False)
    op.create_table('prestamo_libro',
    sa.Column('id_prestamo', sa.Integer(), nullable=False),
    sa.Column('id_libro', sa.Integer(), nullable=True),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('fecha_prestamo', sa.Date(), nullable=True),
    sa.Column('fecha_devolucion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_libro'], ['inventario_libro.id_libro'], ),
    sa.PrimaryKeyConstraint('id_prestamo')
    )
    op.create_index(op.f('ix_prestamo_libro_id_prestamo'), 'prestamo_libro', ['id_prestamo'], unique=False)
    op.create_table('prestamo_objeto',
    sa.Column('id_prestamo', sa.Integer(), nullable=False),
    sa.Column('id_objeto', sa.Integer(), nullable=True),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('fecha_prestamo', sa.Date(), nullable=True),
    sa.Column('fecha_devolucion', sa.Date(), nullable=True),
    sa.Column('estado_entrega', sa.String(length=20), nullable=True),
    sa.Column('talla', sa.String(length=10), nullable=True),
    sa.Column('cantidad_prestada', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_objeto'], ['inventario_objeto.id_objeto'], ),
    sa.PrimaryKeyConstraint('id_prestamo')
    )
    op.create_index(op.f('ix_prestamo_objeto_id_prestamo'), 'prestamo_objeto', ['id_prestamo'], unique=False)
    op.create_table('prueba',
    sa.Column('id_prueba', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_tipo_prueba', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_tipo_prueba'], ['tipo_prueba.id_tipo_prueba'], ),
    sa.PrimaryKeyConstraint('id_prueba')
    )
    op.create_index(op.f('ix_prueba_id_prueba'), 'prueba', ['id_prueba'], unique=False)
    op.create_table('pupitres',
    sa.Column('id_mantenimiento', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.PrimaryKeyConstraint('id_mantenimiento')
    )
    op.create_index(op.f('ix_pupitres_id_mantenimiento'), 'pupitres', ['id_mantenimiento'], unique=False)
    op.create_table('detalle_matricula',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_matricula', sa.Integer(), nullable=True),
    sa.Column('id_tipo', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_matricula'], ['matricula.id_matricula'], ),
    sa.ForeignKeyConstraint(['id_tipo'], ['tipo_concepto.id_tipo'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index(op.f('ix_detalle_matricula_id_detalle'), 'detalle_matricula', ['id_detalle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_matricula_id_detalle'), table_name='detalle_matricula')
    op.drop_table('detalle_matricula')
    op.drop_index(op.f('ix_pupitres_id_mantenimiento'), table_name='pupitres')
    op.drop_table('pupitres')
    op.drop_index(op.f('ix_prueba_id_prueba'), table_name='prueba')
    op.drop_table('prueba')
    op.drop_index(op.f('ix_prestamo_objeto_id_prestamo'), table_name='prestamo_objeto')
    op.drop_table('prestamo_objeto')
    op.drop_index(op.f('ix_prestamo_libro_id_prestamo'), table_name='prestamo_libro')
    op.drop_table('prestamo_libro')
    op.drop_index(op.f('ix_prestamo_instrumento_id_prestamo'), table_name='prestamo_instrumento')
    op.drop_table('prestamo_instrumento')
    op.drop_index(op.f('ix_matricula_id_periodo'), table_name='matricula')
    op.drop_index(op.f('ix_matricula_id_matricula'), table_name='matricula')
    op.drop_table('matricula')
    op.drop_index(op.f('ix_firmas_paz_y_salvo_id_firma'), table_name='firmas_paz_y_salvo')
    op.drop_table('firmas_paz_y_salvo')
    op.drop_table('estudiante_banda')
    op.drop_index(op.f('ix_inventario_libro_id_libro'), table_name='inventario_libro')
    op.drop_table('inventario_libro')
    op.drop_index(op.f('ix_estudiante_id_salon'), table_name='estudiante')
    op.drop_index(op.f('ix_estudiante_id_estudiante'), table_name='estudiante')
    op.drop_table('estudiante')
    op.drop_index(op.f('ix_sesion_usuario_id_sesion'), table_name='sesion_usuario')
    op.drop_table('sesion_usuario')
    op.drop_index(op.f('ix_salon_id_salon'), table_name='salon')
    op.drop_table('salon')
    op.drop_table('rol_usuario')
    op.drop_index(op.f('ix_inventario_instrumento_id_instrumento'), table_name='inventario_instrumento')
    op.drop_table('inventario_instrumento')
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_ubicacion_id_ubicacion'), table_name='ubicacion')
    op.drop_table('ubicacion')
    op.drop_index(op.f('ix_tipo_prueba_id_tipo_prueba'), table_name='tipo_prueba')
    op.drop_table('tipo_prueba')
    op.drop_index(op.f('ix_tipo_concepto_id_tipo'), table_name='tipo_concepto')
    op.drop_table('tipo_concepto')
    op.drop_index(op.f('ix_rol_id_rol'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_periodo_academico_id_periodo'), table_name='periodo_academico')
    op.drop_table('periodo_academico')
    op.drop_index(op.f('ix_inventario_objeto_id_objeto'), table_name='inventario_objeto')
    op.drop_table('inventario_objeto')
    op.drop_index(op.f('ix_categoria_id_categoria'), table_name='categoria')
    op.drop_table('categoria')
    op.drop_index(op.f('ix_auditoria_id_auditoria'), table_name='auditoria')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
