"""añadir documento a usuario

Revision ID: c509474f3370
Revises: dcf0daa6daa6
Create Date: 2026-05-12 13:36:53.186740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c509474f3370'
down_revision: Union[str, None] = 'dcf0daa6daa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('documento', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'documento')
    # ### end Alembic commands ###
