"""add login attempt table

Revision ID: dcf0daa6daa6
Revises: f277dfb1ac7c
Create Date: 2026-05-10 21:02:17.599500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcf0daa6daa6'
down_revision: Union[str, None] = 'f277dfb1ac7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.TIMESTAMP(), nullable=True),
    sa.Column('ultimo_intento', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_login_attempt_id'), 'login_attempt', ['id'], unique=False)
    op.alter_column('sesion_usuario', 'id_usuario',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sesion_usuario', 'token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('sesion_usuario', 'fecha_inicio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sesion_usuario', 'fecha_expiracion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sesion_usuario', 'ultima_actividad',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sesion_usuario', 'activa',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint(None, 'sesion_usuario', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sesion_usuario', type_='unique')
    op.alter_column('sesion_usuario', 'activa',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sesion_usuario', 'ultima_actividad',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sesion_usuario', 'fecha_expiracion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sesion_usuario', 'fecha_inicio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sesion_usuario', 'token',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('sesion_usuario', 'id_usuario',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_login_attempt_id'), table_name='login_attempt')
    op.drop_table('login_attempt')
    # ### end Alembic commands ###
