"""add ultima_actividad

Revision ID: f277dfb1ac7c
Revises: 732d2dfd2ff7
Create Date: 2026-05-10 19:27:06.521668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f277dfb1ac7c'
down_revision: Union[str, None] = '732d2dfd2ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sesion_usuario', sa.Column('ultima_actividad', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sesion_usuario', 'ultima_actividad')
    # ### end Alembic commands ###
